[package]
name = "day-03-mull-it-over"
description = "Advent of code problem 2024 #3: Mull It Over"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { path = '../../aoc'}
nom.workspace = true
anyhow.workspace = true
tracing.workspace = true
