[package]
name = "day-23-amphipod"
description = "Advent of code problem 2021 #23: Amphipod"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { path = '../../aoc'}
nom.workspace = true
anyhow.workspace = true
tracing.workspace = true
