[package]
name = "day-16-aunt-sue"
description = "Advent of code problem 2015 #16: Aunt Sue"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { path = '../../aoc'}
nom.workspace = true
anyhow.workspace = true
tracing.workspace = true
once_cell.workspace = true
