[workspace]
resolver = "2"
members = [ "aoc","_20*/day-*"]

[workspace.dependencies]
anyhow = "1.0.98"
miette = { version = "7.4", features = ["fancy"] }
tracing = "0.1.41"
nom = "7.1.3"
once_cell = "1.19"
