[package]
name = "day-10-hoof-it"
description = "Advent of code problem 2024 #10: Hoof It"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { path = '../../aoc'}
nom.workspace = true
anyhow.workspace = true
tracing.workspace = true
