[package]
name = "day-06-probably-a-fire-hazard"
description = "Advent of code problem 2015 #6: Probably a Fire Hazard"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { path = '../../aoc'}
nom.workspace = true
anyhow.workspace = true
tracing.workspace = true
